ALTER TABLE learning_tests
    ADD COLUMN IF NOT EXISTS min_score_3 INTEGER NOT NULL DEFAULT 2;

ALTER TABLE learning_tests
    ADD COLUMN IF NOT EXISTS min_score_4 INTEGER NOT NULL DEFAULT 3;

ALTER TABLE learning_tests
    ADD COLUMN IF NOT EXISTS min_score_5 INTEGER NOT NULL DEFAULT 4;
