services:

  api:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/product_db
      DB_USER: product
      DB_PASSWORD: product
      APP_JWT_SECRET: U2VjcmV0S2V5U2VjcmV0S2V5U2VjcmV0S2V5U2VjcmV0S2V5MTIzNDU2Nzg=
      GIGACHAT_API_KEY: ${GIGACHAT_API_KEY:-demo-key}
      GIGACHAT_BASE_URL: ${GIGACHAT_BASE_URL:-https://gigachat.devices.sberbank.ru/api/v1}
      GIGACHAT_MODEL: ${GIGACHAT_MODEL:-GigaChat}
    ports:
      - "8080:8080"
